### ISSUE TITLE
IndexError: list index out of range with 1.calculate_probe_identity.py

### ISSUE THREAD

**Issue by thessyed** [hym0405/RNaseH_depletion#4]
Hi Yiming,

When I attempt to run the following command:

`python 1.calculate_probe_identity.py -t representative_genomes_RefSeq/rRNA_sequence/GCA_000807675.2.rRNA.fa -p Ecprobes.tsv -o 2testEu`

I recieve the following error on the 23S probe check:

```
Traceback (most recent call last):
  File "1.calculate_probe_identity.py", line 188, in <module>
    probe_alignedIndex, probe_alignedLength = findProbeMap(probeRNA_alignedSeq, probeRNA_seq, [e[1] for e in probeSet_seq])
  File "1.calculate_probe_identity.py", line 103, in findProbeMap
    probeIndex_alignment.append(probeIndex_original[index])
IndexError: list index out of range
```

I have attached the probe file as a .txt file in case it helps - it is generated using 0.design_probe.py and is not modified from that script's output.
[Ecprobes.txt](https://github.com/hym0405/RNaseH_depletion/files/7646341/Ecprobes.txt) 

Please let me know if there is anything else I can provide to assist with sorting out this issue. Thank you in advance!

**Comment by hym0405** [comment]
Hi,
Thanks for bringing up this issue! It seems this is an issue associated with muscle output and we just updated our script to solve it. I also ran your files with our script and you could find output here. Thank you very much!

[2testEu_output.zip](https://github.com/hym0405/RNaseH_depletion/files/7729895/2testEu_output.zip)

Best,
Yiming
